Walletlib 1.4.0
solana-mobile/mobile-wallet-adapter pull request #904
Opened 2024-07-18 21:50 UTC by Michaelsulistio

# Changes

- Removed the `associationUri` parameter from `initializeMobileWalletAdapterSession` and `useMobileWalletAdapterSession` from `v1.4.0` **(breaking)**
- Instead, the `associationUri` is directly derived from `reactContext.getCurrentActivity().getIntent()` within the Kotlin native module

2024-07-18 21:52 UTC, Michaelsulistio commented on js/packages/mobile-wallet-adapter-walletlib/android/src/main/java/com/solanamobile/mobilewalletadapterwalletlib/reactnative/SolanaMobileWalletAdapterWalletLibModule.kt
> -import com.solana.mobilewalletadapter.common.ProtocolContract
These are lint/formatting changes...

2024-07-18 21:53 UTC, Michaelsulistio commented on js/packages/mobile-wallet-adapter-walletlib/android/src/main/java/com/solanamobile/mobilewalletadapterwalletlib/reactnative/SolanaMobileWalletAdapterWalletLibModule.kt
> +    // very basic/naive implememtion of request cache.
more lint/autoformatting...

2024-07-18 21:54 UTC, Michaelsulistio commented on js/packages/mobile-wallet-adapter-walletlib/android/src/main/java/com/solanamobile/mobilewalletadapterwalletlib/reactnative/SolanaMobileWalletAdapterWalletLibModule.kt
> +        // Get the intent that started this activity
This is the main change.

I've removed the `uriStr` parameter from the API. Instead we use `reactContext.getCurrentActivity()?.getIntent()` to get the Activity's intent and then feed the `intent.getData()` as the URI

2024-07-18 21:54 UTC, Michaelsulistio commented on js/packages/mobile-wallet-adapter-walletlib/src/useMobileWalletAdapterSession.ts
> +function initializeScenario(walletName: string, walletConfig: MobileWalletAdapterConfig) {
Updating the JS API to remove the associationUri param

2024-07-19 15:27 UTC, Funkatronics requested changes

2024-07-19 15:27 UTC, Funkatronics commented on js/packages/mobile-wallet-adapter-walletlib/android/src/main/java/com/solanamobile/mobilewalletadapterwalletlib/reactnative/SolanaMobileWalletAdapterWalletLibModule.kt
> +            return@launch
this should return an error here to notify the caller

2024-07-22 17:31 UTC, Funkatronics approved these changes

2024-07-22 17:43 UTC, merged